### ISSUE TITLE
Validation fails when a schema refers to a schema in other file

### ISSUE THREAD

**Issue by spandananitdgp** [everit-org/json-schema#105]
Hi,

My base schema uses another schema defined in a different file in the same folder as follows:
In schema1.json,
**"$ref": "schema2.json#/Item"**

When I try to validate a json against schema1.json, I get MalformedURLException. Does this validator not support such complex schemas?

**Stacktrace**:
java.io.UncheckedIOException: java.net.MalformedURLException: no protocol: schema2.json
   [testng] 	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:35)
   [testng] 	at org.everit.json.schema.loader.internal.JSONPointer.executeWith(JSONPointer.java:81)
   [testng] 	at org.everit.json.schema.loader.internal.JSONPointer.lambda$forURL$1(JSONPointer.java:133)
   [testng] 	at org.everit.json.schema.loader.internal.JSONPointer.query(JSONPointer.java:152)

**Comment by erosb** [comment]
You have to tell the schema loader where to look for `schema2.json` . The solid way to do that is using absolute URIs in `$ref`s. If that doesn't work for you then you have to explicitly set the base resolution scope. More about it in the [readme](https://github.com/everit-org/json-schema#resolution-scopes) .

**Comment by spandananitdgp** [comment]
I used "$ref" : "file:schemas/schema2.json" in schema and it works. I have a field that is a string (serialized json) that I want to validate against the referred schema.  When I declare the field as:
"data": {
"type": "string",
"$ref" : "file:schemas/schema2.json"
}
it returns valid for any string. Is this use-case even possible with this validator in any of the versions?

**Comment by erosb** [comment]
Hello,

I think in this case you found a bug. The typical usecase for `"$ref"` is that it is used it on its own, without any additional attributes. The [json schema core spec](http://json-schema.org/latest/json-schema-core.html#rfc.section.8) says that "All other properties in a "$ref" object MUST be ignored." . So in this case `"type":"string"` must be ignored by the validator and the `$ref` must be processed. I'm pretty sure about that it would behave correctly for _most_ properties, but not for `"type"`, due to its special role in the schema loading.

Thanks for reporting it. There were some other issues around this area that I wanted to also address in the near future, so maybe I will find some time for it in the upcoming weeks.

If it still doesn't work for you even without the `"type":"string"`, then I would give it a go with `"file://..."` instead of `"file:..."`

**Comment by erosb** [comment]
@spandananitdgp could you make this work for your usecase without `"type":"string"` ?
