### ISSUE TITLE
Using draft V4 in Java8

### ISSUE THREAD

**Issue by RaulGF92** [everit-org/json-schema#108]
Hi everyone, i am using the last version of JSONSchema (I put next to this the maven dependency like probe). When i try change the draft using the same code like instructions, the eclipse compiler say me that: 
> "The method draftV4Support() is undefined for the type SchemaLoader.SchemaLoaderBuilder"

> groupId: com.doctusoft
> artifactId:json-schema-java7
> version:1.4.1
> 

JSONObject rawSchema = new JSONObject("{\"type\": \"integer\",\"minimum\": 0,\"maximum\": 255}");

SchemaLoader loader = SchemaLoader.builder().schemaJson(rawSchema).draftV4Support().build();
Schema schema = loader.load().build();
schema.validate(140);

Could you give me a other way to change the scheme to the V4 draft. Thanks you.

**Comment by erosb** [comment]
Hello, it is unclear for me if you want to use the java8 or the java7 version.

In case you want to use the java8 version, I recommend using version `1.6.0` as explained in the [readme](https://github.com/everit-org/json-schema#maven-installation)

If you want to use the java7 version, then you shouldn't call the `.draftV4Support()` method, since that was introduced in `1.6.0`.

**Comment by RaulGF92** [comment]
Thanks dude, i not copied good the dependencies, when i changed the dependencies the error disappear, so i gonna close the ticket. 

Bye and thank you for your speed.
