### ISSUE TITLE
Assistance needed using org.everit.json.schema

### ISSUE THREAD

**Issue by michaelthoward** [everit-org/json-schema#178]
I am very interested in using org.everit.json.schema for JSON schema validation of objects using org.json data models. 

Unfortunately, I have been unable to get things to work properly using maven + jitpack.io + org.everit.json.schema 1.8.0

I am getting a NoSuchMethod error in org.json.JSONObject.toMap() being called from SchemaLoaderBuilder. 

I have explicitly tried including org.json version 20180130,  but end up with the same results. 

Any assistance would be appreciated. 

Michael

**Comment by erosb** [comment]
Hi! 
The missing `toMap()` method can have 2 reasons I know about:
 - you try to use the library on Android. This is a problem because android has its own org.json package, which is _similar_ to the org.json library used by this schema library, but is not exactly API-compatible, because they diverged - for example the android version doesn't have the `toMap()` method
 - there is some other dependency in your project that overrides the 20180130 version number. You can investigate it using the `mvn dependency:tree` command

**Comment by michaelthoward** [comment]
Thanks for your prompt response!

I am not running on Android ... using Eclipse with JDK 1.8

I have looked at the dependency hierarchy in eclipse and I am not seeing anything. 

Something related ...

Inside eclipse, I don't get the source code for org.everit.json.schema, so it is harder to trace. I don't see this behavior with other mvn packages that I have pulled through github. 

Q: Is there a trick to seeing the source through jitpick.io? 

(I realize that your situation is different since you work on the source)

Thanks!

**Comment by erosb** [comment]
> I have looked at the dependency hierarchy in eclipse and I am not seeing anything.

this looks odd. Can you please create a GitHub repo to share your project with me (at least a minimal skeleton, sufficient to reproduce the problem).

> I don't get the source code for org.everit.json.schema

The URL of the source repository is included in the [`pom.xml`](https://github.com/everit-org/json-schema/blob/master/core/pom.xml#L53), IDEs should use this value to fetch the source. This value never changed since this project started. One thing that can cause problem is that the actual library code is in the `core/` submodule and not in the repository root. AFAIR there is a way to manually attach source code to a jar in eclipse (anyway, I use IntelliJ, so can't look after it locally).
