### ISSUE TITLE
Support for JDK 1.7

### ISSUE THREAD

**Issue by Emmerson-Miranda** [everit-org/json-schema#18]
Hello, I try to use your library, but I get the next exception:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/everit/json/schema/loader/SchemaLoader : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)

I saw in the manifest.mf you are using jdk 1.8.0_60, is it possible update the maven repository with a version compilated with JDK 1.7 ?

Thanks,
Emmerson.

**Comment by erosb** [comment]
Hello @Emmerson-Miranda ,

the library takes a massive use of java8 language features (lambdas, method references) and API calls (stream API). Since javac cannot compile java8 source code to java7 target, I don't think I can provide you a java7-compatible binary. Downgrading the source code to java7 would mean almost a full rewrite.

You are not the first one needing this library for java6/7. In issue #7 I suggested trying out some solutions for compilation, but I didn't try it on my own, and I don't know if @rdruilhe could make it work.

I don't know if you are willing to try those things (streamsupport library and retrolambda), but I would be thankful if you could give some feedback about it.

**Comment by Emmerson-Miranda** [comment]
Hi @erosb,

Our target server not support Java 8 yet, we will try with other server that support it. 

Thanks,
Emmerson.

**Comment by rdruilhe** [comment]
Hello @Emmerson-Miranda,

We did the changes of some part of the code to run on JDK 6.0. But, we do not include the new commits from the master branch. Our changes might be a little old.

Regards.

**Comment by Emmerson-Miranda** [comment]
Thanks @rdruilhe 

Best regards.

**Comment by erosb** [comment]
@rdruilhe could you please share your modifications (including pom.xml changes)?
Just send a PR if you can, I don't mind if it conflicts, but I'd like to work a bit with it (at least to write some docs in the readme about java6/7 compatibility)
