### ISSUE TITLE
Can not create decorator for Schema

### ISSUE THREAD

**Issue by enexusde** [everit-org/json-schema#240]
https://www.tutorialspoint.com/design_pattern/decorator_pattern.htm

	import org.everit.json.schema.Schema;
	
	public class SchemaDecorator extends Schema {
	
		private Schema load;
	
		public SchemaDecorator(Schema load) { // error here, must use super(Builder<?>)
			this.load = load;
		}

**Comment by erosb** [comment]
Hello, for what purpose do you want to use a decorator?

**Comment by enexusde** [comment]
Ok, I guess ill need to implement build() but ill simply return null.

Why is the use of interfaces instead of abstract classes a more bad idea than this workaround? Did I missed something?

**Comment by erosb** [comment]
Hello,

>  ill need to implement build() 

I think it would be better to implement a proper `SchemaDecorator.Builder` class and instantiate the decorator itself from the `build()` method. So on the caller side, instead of directly instantiating the decorator, you would do `SchemaDecorator decorator = SchemaDecorator.builder().build();`. See eg. [NumberSchema](https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/NumberSchema.java) and its builder (and there are a couple of example calls in [its unittest](https://github.com/everit-org/json-schema/blob/master/core/src/test/java/org/everit/json/schema/NumberSchemaTest.java)).

**Comment by enexusde** [comment]
A decorator builder? Hm, means unexpected more code... 
By contract I am not allowed to violate against design principles DIP and KISS.
