### ISSUE TITLE
The validator thinks -0 is a string. not a number

### ISSUE THREAD

**Issue by coderextreme** [everit-org/json-schema#25]
See attached CC.txt JSON document and Schema.txt JSON schema

[CC.txt](https://github.com/everit-org/json-schema/files/105929/CC.txt)
[Schema.txt](https://github.com/everit-org/json-schema/files/105930/Schema.txt)

**Comment by erosb** [comment]
@coderextreme thanks for reporting it. I'm afraid I can't fix it, because this problem is caused by a bug of the underlying org.json API (more specifically the JSONTokener#nextValue() and/or the JSONObject#stringToValue()` methods).

I've tried to find a workaround for it, but it seems the parser notoriously parses the `-0` literal as a string. Trying to convert the `String` instance as a `Number` would not make sense, because if I'd do it that way, then a schema with `{"type" : "number"}` would also accept the `"-0"` JSON string literal as a number (which is against the JSON Schema spec). That would mean fixing a bug by creating a new bug, obviously doesn't make sense.

**Comment by coderextreme** [comment]
Can we use something besides JSONTokener?

**Comment by erosb** [comment]
Well I'm not going to reimplement the tokener from scratch. I'll look after how much time does it take to fix the org.json implementation.

**Comment by coderextreme** [comment]
I was thinking of doing a JSON.parse() and working with that result, but
I'm not familiar with parsers in Java, just JavaScript.

**Comment by coderextreme** [comment]
Or maybe we could switch to gson if it's better.

**Comment by coderextreme** [comment]
I filed an issue here against org.json: https://github.com/douglascrockford/JSON-java/issues/187

**Comment by erosb** [comment]
As the most simple temporary solution I recommend using `-0.0` in your JSON instead of `-0`

**Comment by coderextreme** [comment]
I don’t control the JSON but I can make a recommendation.

John

**Comment by stleary** [comment]
A pull request containing the fix can be found here: https://github.com/stleary/JSON-java/pull/188. Feel free to try it out and let us know whether it addresses the issue.

**Comment by coderextreme** [comment]
Thanks.  Our JSON passes through now (at least that area).  We had over 6300 instances of -0 so this was pretty critical.

John

**Comment by erosb** [comment]
@stleary how are the artifacts deployed to maven central? From my side, fixing this issue will only mean upgrading (in my pom.xml) to the version containing the bugfix.
