### ISSUE TITLE
Ordered schema properties

### ISSUE THREAD

**Issue by sly-x86** [everit-org/json-schema#268]
Hello,
Is there any way to preserve properties order with ObjectSchema? I want to use this meta info to make some validations. For now, ObjectSchema supplied with HashMap to store properties and as a result, we have randomly ordered keys.

**Comment by erosb** [comment]
Hello @sly-x86 ,

no, since json objects are unordered, the json schema also doesn't contain any keywords for validating any kind of order of keys. Also, the org.json library (used by this schema library) doesn't support any other object storage than HashMap (though it is a widely requested feature) - see [their wiki](https://github.com/stleary/JSON-java/wiki/FAQ#why-isnt-ordering-allowed-in-jsonobjects).

**Comment by sly-x86** [comment]
Is there any way to replace default builder? I think Replacing HashMap with LinkedHashMap would help
