### ISSUE TITLE
Invalid error when JSON is validated with JSON Schema (oneOf)

### ISSUE THREAD

**Issue by octavianN** [everit-org/json-schema#276]
If I validate the following JSON instance with the JSON Schema, I get an error `#/val_validationRule: #: 2 subschemas matched instead of one`.
The instance is valid conform with the first subschema.

```json
{
    "val_validationRule": {
        "isPresent": "isPresent",
        "occurs": 1
    }
}
```

```json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"val_validationRule": {
	      "type": "object",
	      "oneOf": [
	        {
	          "properties": {
	            "isPresent": { "type": "string" },
	            "occurs": { "type": "integer", "minimum": 1 }
	          }
	        },
	        {
	          "properties": {
	            "isNotPresent": { "type": "string" },
	            "occurs": { "type": "integer", "minimum": 1 }
	          }
	        }
	      ]
	    }
   }
}
```

**Comment by erosb** [comment]
This is a schema bug, as the exception says, the instance is valid against the 2nd subschema too. It is valid because you just declared the schema of `"isNotPresent"` but you didn't make it mandatory, and also both subschemas permit additional properties.

If I understand correctly what you try to achieve then I suggest
 * adding these to the first subschema (adjacent to `"properties"`): "required": ["isPresent"], "additionalProperties": false`
 * adding these to the second subschema (adjacent to `"properties"`): "required": ["isNotPresent"], "additionalProperties": false`

**Comment by octavianN** [comment]
Thanks for your answer. Yes, it seems to be a problem in the schema. 
This example is from the JLIFF JSON Schema:
https://github.com/oasis-tcs/xliff-omos-jliff/tree/master/JLIFF-schema-draft
Maybe I will add an issue to there project.
