### ISSUE TITLE
Question about $ref resolver

### ISSUE THREAD

**Issue by acmitch** [everit-org/json-schema#286]
Is there an easy way to resolve a reference schema statically given the pointer value and the original schema?

Note: I think what I need is the ```org.everit.json.schema.loader.ReferenceLookup#lookup``` method, however, it is package-private.

**Comment by erosb** [comment]
Hi!

Yes, that's the method you need. Quite long ago we stopped exposing any functionality on the public API that we don't intentionally want to make avaliable, because that just makes refactoring harder (more signatures that have to remain backward-compatible).

In this case unfortunately I think it will stay package-private, because to use the `lookup()` method, you need a `ReferenceLookup` instance, and its constructor depends on the `LoadingState` class, which is again package-private, and I don't really want to make that `public`, for the reasons said above.

By the way if you are dealing only with intra-document references, then the org.json library already provides a `JSONPointer` class which can evaluate a json pointer on a given json document. It is a part of the `$ref` resolution process, I'm not sure if that fits your needs. Can you please tell a bit more about your usecase?

**Comment by acmitch** [comment]
I was worried that might be the case.  Our team needs to flatten the JsonSchema to dot-notation. For example:

```
// Given
{
  "type": "object",
  "properties": {
    "street_zip":  { "type": "number" },
    "street_name": { "type": "string" },
    "street_type": { "type": "string","enum": ["Street", "Avenue", "Boulevard"]},
    "street_info": {"type": "object"},
    "street_misc": {"type": "object", "properties": {
        "resident_name": {"type": "string"},
        "resident_phone": {"type": "number"}
    }}
  }
}

// Becomes
$.street_zip.number, 
$.street_misc.resident_name.string
$.street_misc.resident_phone.number
$.street_type.enum 
$.street_info
$.street_name.string
```
However, we run into problems when a ```$ref``` is encountered. In order to flatten nested ```$ref``` elements we need a method which as described above, will resolve a reference schema statically given the pointer value.

The purpose of flattening the JsonSchema is that our organization would like to configure business rules based on JsonSchemas.  To do this we can flatten the JsonSchema using the flattened values as the lookup key for which rules to apply.

Then when JSON data is processed we flatten it as well and retrieve which rules to apply, by matching the flattened keys from the data to the flattened json-schema keys.

**Comment by erosb** [comment]
I see. Have you checked [this library](https://github.com/AndersDJohnson/jackson-json-reference) ?

**Comment by acmitch** [comment]
I have not, we will give it a shot tomorrow. Thanks a lot for the help and quick responses. I will close.
