### ISSUE TITLE
Question: "required" errors are coming without the fieldName in the pointerToViolation

### ISSUE THREAD

**Issue by NaveenGurram** [everit-org/json-schema#331]
Hi @erosb 

  I have a question, in case of validation exception for "required", we get back errors but violation pointer always points to the root of the exception without field.

in below example, at "#" there are three fields missing and at "#/field4" there are two fields missing but if you see the validation exception json pointer is at "#" or "#/field4"

so my question was is it possible to put the field name in the **pointerToViolation** ?

currently the field that is missing is **only** in the message it isn't anywhere else for me to grab. 

**Json Schema**

``` json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://json-schemas.finra.org/schemas/root.json",
  "title": "CRS",
  "type": "object",
  "$comment": "This is the parent schema for the CRS filing.",
  "required": ["field1", "field2", "field3"],
  "additionalProperties": false,
  "properties": {
    "field1": {
      "title": "field1",
      "type": "string"
    },
    "field2": {
      "title": "field1",
      "type": "string"
    },
    "field3": {
      "title": "field1",
      "type": "string"
    },
    "field4": {
      "required": ["subfield1","subfield2"],
      "properties": {
        "subfield1": {
          "title": "sub-field1",
          "type": "string"
        },
        "subfield2": {
          "title": "sub-field1",
          "type": "string"
        }
      }
    }
  }
}
```

**Input**

``` json
{
 "field4": {}
}
```

**Validation Exception**

``` json
{
  "schemaLocation": "#",
  "pointerToViolation": "#",
  "causingExceptions": [
    {
      "schemaLocation": "#",
      "pointerToViolation": "#",
      "causingExceptions": [],
      "keyword": "required",
      "message": "required key [field1] not found"
    },
    {
      "schemaLocation": "#",
      "pointerToViolation": "#",
      "causingExceptions": [],
      "keyword": "required",
      "message": "required key [field2] not found"
    },
    {
      "schemaLocation": "#",
      "pointerToViolation": "#",
      "causingExceptions": [],
      "keyword": "required",
      "message": "required key [field3] not found"
    },
    {
      "schemaLocation": "#/properties/field4",
      "pointerToViolation": "#/field4",
      "causingExceptions": [
        {
          "schemaLocation": "#/properties/field4",
          "pointerToViolation": "#/field4",
          "causingExceptions": [],
          "keyword": "required",
          "message": "required key [subfield1] not found"
        },
        {
          "schemaLocation": "#/properties/field4",
          "pointerToViolation": "#/field4",
          "causingExceptions": [],
          "keyword": "required",
          "message": "required key [subfield2] not found"
        }
      ],
      "message": "2 schema violations found"
    }
  ],
  "message": "5 schema violations found"
}

```

**Comment by erosb** [comment]
Hello @NaveenGurram ,

the `pointerToViolation` value itself is correct, since the violating object is the object which doesn't have the required property. So the `"required"` keyword defines a validation constraint on the containing object and not on its field.

It would make sense though to hold the name of the missing property in a separate field so that you wouldn't have to parse the exception message (which is pain, I know). The ideal solution - in case we would be on a greenfield project - would be creating exception subclasses for each json schema keyword, but this is barely possible at this point.

So I think realistically we could improve `ValidationException` so that it contains an arbitary `Map<String, Object>` attribute set for each exception which holds additional error-specific information for programmatic processing. I think this can fit into the next release - no ETA though, the last release was actually yesterday...

**Comment by NaveenGurram** [comment]
@erosb 

  thanks for the response.

  yeah you are right about the  `pointerToViolation` value being correct.

  no worries on the fix, for now I am extracting it from the message, as long as message doesn't change I am good for now.
