### ISSUE TITLE
[Question/Suggestion] Move away from JitPack?

### ISSUE THREAD

**Issue by slisaasquatch** [everit-org/json-schema#338]
I used to use and love JitPack as well, but JitPack was down for multiple days in the past few weeks, and their support was virtually non-existent. That basically destroyed my trust and I'm moving all of my projects to Bintray/JCenter.

Are there plans of moving away from JitPack? I know deploy Maven Central is a huge pain, but JCenter is really easy and not too far off from JitPack in terms of ease of use. Is that a viable option?

**Comment by erosb** [comment]
Hello, some recent versions [are deployed to maven central](https://search.maven.org/search?q=com.github.erosb), you can use that as a plan-b if you need to. Maven central is not a primary distribution channel though, and artifacts can be deployed later than the jitpack release. I don't  think that moving to bintray/jcenter could be a final solution, because some users need the maven central artifacts because jitpack doesn't fit their software source compliance policies - In don't think this would be different with any of the other 3rd-party providers.

**Comment by slisaasquatch** [comment]
Thanks! I'll close the ticket.
