### ISSUE TITLE
E-Mail not validating

### ISSUE THREAD

**Issue by alexander-raich** [everit-org/json-schema#354]
Hello

**Given**:
```        
JSONObject rawSchema = new JSONObject(new JSONTokener("{\n" +
                "  \"$schema\": \"http://json-schema.org/draft-07/schema#\",\n" +
                "  \"properties\": {\n" +
                "    \"email\": {\n" +
                "          \"description\": \"@property Standard email address\",\n" +
                "          \"type\": \"string\",\n" +
                "          \"format\": \"email\"\n" +
                "    }\n" +
                "  }\n" +
                "}"));
        Schema schema = SchemaLoader.load(rawSchema);

        schema.validate(new JSONObject("{\n" +
                "\t\"email\": \"test@test.test\"\n" +
                "}"));
```
**Exptected**:
"test@test.test" validates (it does using https://www.jsonschemavalidator.net/)
![image](https://user-images.githubusercontent.com/18245247/74820436-4a4fb880-5302-11ea-99ac-c6dd4939388c.png)

**Actual**:
```
Exception in thread "main" org.everit.json.schema.ValidationException: #/email: [test@test.test] is not a valid email address
```

Am I missing something?

Thanks
Alex

**Comment by erosb** [comment]
Hello, we use `commond-validator:commons-validator:1.6` under the hood, which seems to support only known TLDs. The best would be to get this fixed in that project, and there seem to be a jia issue for this already: https://issues.apache.org/jira/browse/VALIDATOR-324

We may consider using an other validator library, since the TLD validation is a problem for the `"hostname"` format too, but I'm not sure if it will happen in any near releases.

If you need to get this fixed urgently, the I suggest using a custom format validator for `"email"`. See the [readme](https://github.com/everit-org/json-schema#format-validators) for explanation about implementing it.

Thanks for reporting the problem.

**Comment by alexander-raich** [comment]
Hi erosb

Thanks for the quick reply. We will work around using a custom pattern. Thanks for the information regarding commons-validator. 

Have a good day
Alex
