### ISSUE TITLE
How to provide list of enum supported in error message

### ISSUE THREAD

**Issue by Suchismita1tutun** [everit-org/json-schema#362]
I am using enum to restrict the value of a field of type string. When anything that is not in the list is provided it's throwing error as "[#/config/option: cleanupp is not a valid enum value]" . This is working as expected. But it doesn't provide the list of valid enums as a part of error message. 

For example: If the supported values in this case if ["cleanup","dryrun"] then I am expecting the errors mgs as "[#/config/option: cleanupp is not a valid enum value, Supported options are ["cleanup","dryrun"] ]"

Is there any way out to get such a custom error ? Any help would be appreciated

**Comment by erosb** [comment]
Hello, we don't include any user-supplied information, neither from the schema nor from the instance being validated, this is an intentional design decision.

When you catch the `ValidationException`, you can call its `ValidationException#getViolatedSchema()`. Then you can check if it is an `EnumSchema`, which has a `#getPossibleValues()` method returning the set you are looking for, so given that you can generate a more detailed error message.

**Comment by Suchismita1tutun** [comment]
Thanks a lot for your quick response. ValidationException.getViolatedSchema() is returning me the entire schema which is not an enum schema. It is of class org.everit.json.schema.CombinedSchema.  Only a field of this schema is an enum. How to get the EnumSchema ?

**Comment by erosb** [comment]
Traverse the tree provided (recursively) by `ValidationException#getCausingExceptions()`. See the [Investigating failures](https://github.com/everit-org/json-schema#investigating-failures) section of the manual for further information.

**Comment by Suchismita1tutun** [comment]
Yeah I did follow that documentation and got the individual schema. But as the field is of type String with enums , the correspoding the validationSchema is of type StringSchema. How to get the Enum Schema of it. Thanks a lot again for your quick help

**Comment by Suchismita1tutun** [comment]
Resolved the issue. Thanks a lot for your help

**Comment by Suchismita1tutun** [comment]
Closing it
