### ISSUE TITLE
similar library on central maven repo

### ISSUE THREAD

**Issue by js-s** [everit-org/json-schema#375]
Hi,
I have a question about this library. In the library description there is information that from version 1.6 this library is no longer available in the central repository of Maven. I found a very similar, basically identical library on mvnrepository (https://mvnrepository.com/artifact/com.github.erosb/everit-json-schema/1.12.1). However, it has a different group and artifact. Can you tell me if this is your code? And if so, why is it under a different name and will next versions of your library also appear in the central repository of Maven?

I will be grateful for your response.

**Comment by erosb** [comment]
Hello @js-s , yes, it is the same library. JitPack is considered as the primary distribution channel, but occasionally I also create maven central releases too, for people who need to stick to maven central as a software repository, because of compliance reasons. The maven central version is sometimes released later than the jitpack artifact, but it contains the same bytecode (under different maven coordinates).

**Comment by js-s** [comment]
thanks @erosb for the information. I wasn't sure how freely I could use this code.

**Comment by ricardozanini** [comment]
Can you please link this issue in the README file where you mention the distribution on JitPack only? It would be useful for other users to follow the same path. I had the same problem regarding compliances issues as well :)
