### ISSUE TITLE
log4j:jar:1.2.17 dependency has issue idenetified by whitesource 

### ISSUE THREAD

**Issue by BoDING1007** [everit-org/json-schema#450]
Hi, recent whitesource in our application has identified that json-schema have WhiteSource issue. Due to that it used commons-validator 1.7 which still uses commons-logging 1.2.  commons-logging 1.2 uses log4j:jar:1.2.17 which has the issue identified by WhiteSource.
Any solution?

**Comment by erosb** [comment]
What is the problem? AFAIK log4j 1.x is not vulnerable.

**Comment by BoDING1007** [comment]
![image](https://user-images.githubusercontent.com/24220535/149638222-0fc66d41-6944-4f16-906a-d1acb4990383.png)

Here is what we got from whitesource.
Included in Log4j 1.2 is a SocketServer class that is vulnerable to deserialization of untrusted data which can be exploited to remotely execute arbitrary code when combined with a deserialization gadget when listening to untrusted network traffic for log data. This affects Log4j versions up to 1.2 up to 1.2.17.

**Comment by erosb** [comment]
Feel free to raise a PR fixing the problem. It doesn't look like an actually exploitable vulnerability, rather something needing a fix due to compliance reasons, so I don't plan to work on it on my own.

Alternatively, you can exclude the `commons-validator` from your project, if loosing support for a couple of `"format"`s is acceptable. It is a [supported configuration](https://github.com/everit-org/json-schema#excluding-dependencies).
