### ISSUE TITLE
Is unevaluatedProperties keyword supported?

### ISSUE THREAD

**Issue by Gourav2912** [everit-org/json-schema#503]
Is unevaluatedProperties keyword supported in validation library?

**Comment by erosb** [comment]
Hello, no it isn't. This library is in maintenance mode (only critical bugfixes & dependency updates are released). Since `"unevaluatedProperties"` keyword isn't part of the json schema specification draft-7, it won't be added here (see the [deprecation notice](https://github.com/everit-org/json-schema#deprecation-notice)).

The currently active project is https://github.com/erosb/json-sKema which supports draft2020-12 (including `"unevaluatedProperties"`).

**Comment by Gourav2912** [comment]
Thanks @erosb  for quick reply. Possible to upgrade to java version 17 for new library
