### ISSUE TITLE
Is there a way to tie this to any JPath implementation?

### ISSUE THREAD

**Issue by DavidThi808** [everit-org/json-schema#90]
We want to use JPath withc schema support so it can do inequalities on dates. Is there any JPath implementation that works with json-schema?

thanks - dave

**Comment by erosb** [comment]
Hello @DavidThi808 , I'm not sure if I understand your usecase (and I also have only a very basic knowledge about JPath). Could you please provide a little more details about your usecase?

**Comment by DavidThi808** [comment]
Hi Bence;

Happy to. Let's say I have some JSON with "birthdate : '1965-02-27'". This value is a date. I know that, you know that, and with a schema the schema knows that.

Now let's look at JPath. We can have a JPath statement like "$.employee.birthdate" In all the JPath implementations I've seen, it only knows numbers, booleans, and strings. So this is a string with the value "1965-02-27" and I could not do a JPath select like "$.employee.birthdate <= '1965-01-01'".

But if the JPath implementation knows that birthdate is a date, then I could do that select.

thanks - dave

**Comment by erosb** [comment]
Hello Dave,

this looks like an interesting problem. I doubt you will find a solution which works out of the box. A few thoughts:

 * I'm not sure of JPath is the same things as JsonPath. I found only a javascript library called JPath
 * if your purpose is only being able to compare dates, then I think you don't need any schema-driven support, since lexical string comparison will work (assuming that all your dates are in `yyyy-mm-dd` format).
 * if you want have a more generic problem, and you want a query language for json documents which supports overloaded operators (eg. comparison operators behave differently depending on the schema of the operands), then it sounds like an interesting problem, but most probably it is an unexplored area, and you won't find tools for this
 * in case you want to build an implementation for such a language, using a schema library (this one, or any other) will help, since `Schema` objects are easier to consume and interpret than the raw JSON.

**Comment by DavidThi808** [comment]
Hi Bence;

- Yep JsonPath
- Good point. But getting them back as typed values on a getValue() is useful too when say populating a chart.
- That's what I'm finding too.
- Yep, I'm thinking of merging your code into [the JsonPath project](https://github.com/json-path/JsonPath).

thanks - dave
